# Generated by Django 4.2.4 on 2023-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/carousel/images'),
        ),
    ]
