# Generated by Django 4.2.5 on 2023-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_temporaryphonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryphonenumber',
            name='verified',
        ),
        migrations.AddField(
            model_name='temporaryphonenumber',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
