# Generated by Django 4.2.5 on 2023-10-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customuser_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
