# Generated by Django 4.2.5 on 2023-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_size_alter_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Uploaded_Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('client_note', models.TextField(blank=True, null=True)),
                ('top_lenght', models.CharField(blank=True, max_length=15, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=15, null=True)),
                ('Round_chest', models.CharField(blank=True, max_length=15, null=True)),
                ('sleeve_lenght', models.CharField(blank=True, max_length=15, null=True)),
                ('neck', models.CharField(blank=True, max_length=15, null=True)),
                ('round_arm', models.CharField(blank=True, max_length=15, null=True)),
                ('arm_hole', models.CharField(blank=True, max_length=15, null=True)),
                ('front_chest', models.CharField(blank=True, max_length=15, null=True)),
                ('back_chest', models.CharField(blank=True, max_length=15, null=True)),
                ('cuff', models.CharField(blank=True, max_length=15, null=True)),
                ('short_sleeve_width', models.CharField(blank=True, max_length=15, null=True)),
                ('three_quarter_width', models.CharField(blank=True, max_length=15, null=True)),
                ('long_sleeve_width', models.CharField(blank=True, max_length=15, null=True)),
                ('trouser_lenght', models.CharField(blank=True, max_length=15, null=True)),
                ('waist', models.CharField(blank=True, max_length=15, null=True)),
                ('lap', models.CharField(blank=True, max_length=15, null=True)),
                ('knee', models.CharField(blank=True, max_length=15, null=True)),
                ('calf', models.CharField(blank=True, max_length=15, null=True)),
                ('ankle', models.CharField(blank=True, max_length=15, null=True)),
                ('BR', models.CharField(blank=True, max_length=15, null=True)),
                ('RBR', models.CharField(blank=True, max_length=15, null=True)),
                ('agbada_lenght', models.CharField(blank=True, max_length=15, null=True)),
                ('agbada_shoulder', models.CharField(blank=True, max_length=15, null=True)),
                ('agbada_sleeve', models.CharField(blank=True, max_length=15, null=True)),
                ('cap', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
