# Generated by Django 4.2.5 on 2023-10-22 10:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_user_uploaded_measurement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_uploaded_measurement',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
