# Generated by Django 4.2.4 on 2023-09-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_clientmeasurements_br_clientmeasurements_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='top_design_image_3',
        ),
        migrations.AddField(
            model_name='jobs',
            name='cap_fabric_image',
            field=models.ImageField(blank=True, null=True, upload_to='cap_fabric'),
        ),
    ]
