# Generated by Django 4.2.5 on 2023-10-17 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Yes')], default='Mr', max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+234', help_text='Enter a valid phone number in E.164 format.', max_length=128, null=True, region=None)),
                ('address', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('client_note', models.TextField(blank=True, null=True)),
                ('size', models.CharField(choices=[('C', 'Children'), ('XS', 'Xtra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large'), ('XXL', 'Xtra Xtra Large')], default='L', max_length=50)),
                ('top_lenght', models.CharField(blank=True, max_length=15, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=15, null=True)),
                ('Round_chest', models.CharField(blank=True, max_length=15, null=True)),
                ('sleeve_lenght', models.CharField(blank=True, max_length=15, null=True)),
                ('neck', models.CharField(blank=True, max_length=15, null=True)),
                ('round_arm', models.CharField(blank=True, max_length=15, null=True)),
                ('arm_hole', models.CharField(blank=True, max_length=15, null=True)),
                ('front_chest', models.CharField(blank=True, max_length=15, null=True)),
                ('back_chest', models.CharField(blank=True, max_length=15, null=True)),
                ('cuff', models.CharField(blank=True, max_length=15, null=True)),
                ('short_sleeve_width', models.CharField(blank=True, max_length=15, null=True)),
                ('three_quarter_width', models.CharField(blank=True, max_length=15, null=True)),
                ('long_sleeve_width', models.CharField(blank=True, max_length=15, null=True)),
                ('trouser_lenght', models.CharField(blank=True, max_length=15, null=True)),
                ('waist', models.CharField(blank=True, max_length=15, null=True)),
                ('lap', models.CharField(blank=True, max_length=15, null=True)),
                ('knee', models.CharField(blank=True, max_length=15, null=True)),
                ('calf', models.CharField(blank=True, max_length=15, null=True)),
                ('ankle', models.CharField(blank=True, max_length=15, null=True)),
                ('BR', models.CharField(blank=True, max_length=15, null=True)),
                ('RBR', models.CharField(blank=True, max_length=15, null=True)),
                ('agbada_lenght', models.CharField(blank=True, max_length=15, null=True)),
                ('agbada_shoulder', models.CharField(blank=True, max_length=15, null=True)),
                ('agbada_sleeve', models.CharField(blank=True, max_length=15, null=True)),
                ('cap', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_done', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=50)),
                ('measurement_confirmed', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=50)),
                ('any_issue', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.TextField(blank=True, help_text='Enter name + fabrictype or color', max_length=50, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('AMENDS', 'Amends')], default='PRODUCT', max_length=50)),
                ('fabric_image_1', models.ImageField(blank=True, null=True, upload_to='work/jobs/fabric_images')),
                ('fabric_image_2', models.ImageField(blank=True, null=True, upload_to='work/jobs/fabric_images')),
                ('fabric_yardage', models.IntegerField(blank=True, null=True)),
                ('fabric_note', models.TextField(blank=True, null=True)),
                ('top_design_image_1', models.ImageField(blank=True, null=True, upload_to='work/jobs/top_designs')),
                ('top_design_image_2', models.ImageField(blank=True, null=True, upload_to='work/jobs/top_designs')),
                ('top_design_note', models.TextField(blank=True, null=True)),
                ('trouser_design_image', models.ImageField(blank=True, null=True, upload_to='work/jobs/trouser_designs')),
                ('trouser_design_note', models.TextField(blank=True, null=True)),
                ('agbada_design_image', models.ImageField(blank=True, null=True, upload_to='work/jobs/agbada_designs')),
                ('agbada_design_note', models.TextField(blank=True, null=True)),
                ('cap_fabric_image', models.ImageField(blank=True, null=True, upload_to='work/jobs/cap_fabric')),
                ('cap_design_image', models.ImageField(blank=True, null=True, upload_to='work/jobs/cap_designs')),
                ('cap_design_note', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.clients')),
                ('workers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_amount', models.IntegerField(blank=True, null=True)),
                ('trouser_amount', models.IntegerField(blank=True, null=True)),
                ('agbada_amount', models.IntegerField(blank=True, null=True)),
                ('cap_amount', models.IntegerField(blank=True, null=True)),
                ('name', models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.job_operation')),
            ],
        ),
        migrations.AddField(
            model_name='job_operation',
            name='name',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.jobs'),
        ),
        migrations.CreateModel(
            name='Job_delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.job_operation')),
            ],
        ),
    ]
