# Generated by Django 4.2.4 on 2023-09-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='fabric_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='work/fabric_images'),
        ),
    ]
