# Generated by Django 4.2.5 on 2023-10-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='user',
        ),
    ]
