# Generated by Django 4.2.5 on 2023-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_worker_profile_delete_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
