# Generated by Django 4.2.5 on 2023-10-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_remove_worker_profile_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_profile',
            name='verified_worker',
            field=models.BooleanField(default=False),
        ),
    ]
