# Generated by Django 4.2.5 on 2023-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_worker_profile_verified_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_profile',
            name='sex',
            field=models.CharField(blank=True, default='Male', max_length=10, null=True),
        ),
    ]
