# Generated by Django 4.2.4 on 2023-09-15 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0006_alter_jobs_agbada_design_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='top_worker',
        ),
        migrations.AddField(
            model_name='jobs',
            name='workers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workers',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+234', help_text='Enter a valid phone number in E.164 format.', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.TextField(blank=True, help_text='Enter name + fabrictype or color', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
