# Generated by Django 4.2.4 on 2023-09-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_remove_jobs_top_worker_jobs_workers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmeasurements',
            old_name='_3quarter_width',
            new_name='three_quarter_width',
        ),
        migrations.RemoveField(
            model_name='clientmeasurements',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clientmeasurements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='job_title',
        ),
        migrations.AddField(
            model_name='clientmeasurements',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientmeasurements',
            name='measurement_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.clients'),
        ),
    ]
