# Generated by Django 4.2.4 on 2023-09-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_rename__3quarter_width_clientmeasurements_three_quarter_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
