# Generated by Django 4.2.4 on 2023-09-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_rename_client_name_clientmeasurements_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='name',
        ),
    ]
