# Generated by Django 4.2.4 on 2023-09-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_clients_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.clients'),
        ),
    ]
