# Generated by Django 4.2.4 on 2023-09-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_rename_name_clients_measurement_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='name',
            new_name='job_name',
        ),
    ]
