# Generated by Django 4.2.5 on 2023-10-13 13:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_alter_jobs_agbada_design_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='user',
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+234', help_text='Enter a valid phone number in +234 format.', max_length=128, null=True, region=None),
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
