# Generated by Django 4.2.5 on 2023-10-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_remove_clients_user_alter_clients_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='workers',
        ),
    ]
