# Generated by Django 4.2.5 on 2023-10-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
