# Generated by Django 4.2.5 on 2023-10-15 08:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+234', help_text='Enter a valid phone number in E.164 format.', max_length=128, null=True, region=None),
        ),
    ]
