# Generated by Django 4.2.5 on 2023-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_verify_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_worker',
            field=models.BooleanField(default=False),
        ),
    ]
