"""
Django settings for tailorApp project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from .settings import *


# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False

ALLOWED_HOSTS = [
    "neeyee.store",   # production url main host
    "www.neeyee.store", #sub-domain for roduction     
    "test.neeyee.store", #main host for testing url
    "work.neeyee.store", # production url for work module
    "work-test.neeyee.store", # testing url for work module
    "gladmin.neeyee.store", # production url for admin
    "gladmin-test.neeyee.store", #testing url for admin
    "account.neeyee.store",    #production url for account module - allauth
    "account-test.neeyee.store",   #testing url for account module - allauth

]


#log error into error.log file in production
LOGGING = {
'version': 1,
'disable_existing_loggers': False,
'handlers': {
    'file': {
        'level': 'DEBUG',
        'class': 'logging.FileHandler',
        'filename': 'error.test',
    },
},
'loggers': {
    'django': {
        'handlers': ['file'],
        'level': 'DEBUG',
        'propagate': True,
    },
},
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD':  config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }, 
}




#email settings
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# Access the storage credentials from environment variables
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL')
AWS_S3_REGION_NAME = 'auto'
AWS_DEFAULT_ACL = 'public-read'


#serve static files
#serve static files during production
#DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#MEDIA_URL = f"https://s3.us-east-005.backblazeb2.com/media/"
#STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
#STATIC_URL = f"https://s3.us-east-005.backblazeb2.com/static/"

STATIC_ROOT = config('STATIC_ROOT')
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_ROOT = config('MEDIA_ROOT')
MEDIA_URL = "/media/"