"""
Django settings for tailorApp project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from .settings import *








# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

 
# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True
#TEMPLATE_DEBUG = True

ALLOWED_HOSTS = ['*']




# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# For development, you might want to use SQLite as your database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Use a simple cache for development
#CACHES = {
 #   'default': {
  #      'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
  #      'LOCATION': 'unique-snowflake',  # Change this in production
   # }
#}


# Add django-debug-toolbar for debugging purposes
#INSTALLED_APPS += ['debug_toolbar']
#MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']


#email settings
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# Serve static and media files locally during development

STATIC_ROOT = os.path.join(BASE_DIR, 'statics')
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static",]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'